### PR TITLE
Containerized the Application

### PR DESCRIPTION
**Pull request by obafemitayor**
### Background
I was trying to contribute to [this](https://github.com/jovialcore/whatcompstack-FE/issues/41) but spent several hours trying to get the repo working on my PC due to issues with installing PHP version greater than 8. After spending almost a day on this, I decided to run the application using a container and that worked. So I am creating this PR as an option to run the application in case other contributors get stuck like me

### Testing Strategy
image

### CODE REVIEW

**Comment by jovialcore** [comment]
Hi @obafemitayor  thank you for taking the time to send a pull request. I will take a look.

**Comment by obafemitayor** [comment]
> Hi @obafemitayor thank you for taking the time to send a pull request. I will take a look.

@jovialcore The PR is still in draft phase. I will let you know once it is ready for a review

**Comment by obafemitayor** [comment]
> > Hi @obafemitayor thank you for taking the time to send a pull request. I will take a look.
> 
> @jovialcore The PR is still in draft phase. I will let you know once it is ready for a review

@jovialcore It is ready for review now. I have updated the description of the PR to explain why the PR is needed

**Comment by jovialcore** [comment]
@obafemitayor super thanks. I appreciate the PR. I will take a look.

**Comment by obafemitayor** [comment]
> @obafemitayor super thanks. I appreciate the PR. I will take a look.

Hello @jovialcore, were you able to find some time to review the PR?.

**Comment by jovialcore** [comment]
> Hello @jovialcore, were you able to find some time to review the PR?

Hi @obafemitayor not yet. Also, I had planned to push an updated version of the code today that is properly in sync with what is on prod. When I do this, I want to kindly ask that you check if your recent PR will still work with the  docker implementation, if it works (it should though), Great I will approve. I appreciate. 


Hope it's fine ?

**Comment by obafemitayor** [comment]
> > Hello @jovialcore, were you able to find some time to review the PR?
> 
> Hi @obafemitayor not yet. Also, I had planned to push an updated version of the code today that is properly in sync with what is on prod. When I do this, I want to kindly ask that you check if your recent PR will still work with the docker implementation, if it works (it should though), Great I will approve. I appreciate.
> 
> Hope it's fine ?

@jovialcore Yes sure

**Comment by jovialcore** [comment]
Alright! On it !

**Comment by obafemitayor** [comment]
> Alright! On it !

@jovialcore I have just merged this branch with the latest changes and it still works. Here is the test evidence
image

**Review by jovialcore — APPROVED** [review]

**Comment by jovialcore** [comment]
Thanks.

**Pull request merged**
