### PR TITLE
Refactor/store company data validation

### PR DESCRIPTION
**Pull request by codejutsu1**
Moving the validation rules of the store company data to a request file.

### CODE REVIEW

**Comment by codejutsu1** [comment]
I am always having 2 commit changes whenever I pull to the dev branch but 1 commit change (which I intend to have) when ever I pull to the main branch.

**Comment by jovialcore** [comment]
Alright. this is fine. Thank you so much.  Please one more thing, moving on, we want to make PRs to a new branch that can be given the name of the issue you want to fix. This will help the maintainers to test your changes seperately. That should work yeah ? Please see updated [contribution md](https://github.com/jovialcore/whatcompstack-BE/blob/main/CONTRIBUTING.md)

**Comment by codejutsu1** [comment]
That's really a good suggestion, but I can't create a new branch in your repo. Mayb I don't have permission to do so.

**Comment by codejutsu1** [comment]
Hello, I haven't heard from you @jovialcore

**Pull request merged**
